apiVersion: vegeta.k8s.io/v1beta1
kind: Vegeta
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: distributed-vegeta-example
spec:
  # here is the cmd-line vegeta
  attack: echo "GET http://localhost/" | vegeta attack -duration=5s
  # here is the number of attack performed. Default is one
  numAttack: 2
